### PR TITLE
CIF-1500 - Setup IT project for Venia Demo

### PR DESCRIPTION
**Pull request by cjelger**
This adds integrations tests for the four "main" page types of the Venia demo: landing page, product page, category page, and search page. The tests are pretty simple, they fetch the pages and check a few fields like product and category name, navigation menu, products in category, etc. This ensures that at least the demo works with all the components: CIF Add-On, CIF components, etc. We could extend these tests with the new `ui.tests` project that has recently been added to the AEM Archetype.

Because we cannot deploy a docker-based Magento instance and access the AWS Artifactory in the mean time, the integration tests are based on the mock GraphQL Magento servlet from the CIF Components Library.

**Note**: I already added extra checks for the breadcrumb but this has not been released yet so I commented them out. We should enable them after we release the components and update the dependency for Venia.

This PR also makes quite some changes to the caching done during the build, to separate the `cloud` and `classic` caches and deploy them in layers because the `it.tests` build downloads extra dependencies only when it is executed with the `-Plocal` profile (this comes from the OOTB AEM Archetype). Note that I had to use CircleCI parameters for that because one cannot use environment variables in cache names.

Also the integration tests don't upload any coverage because they don't cover any java files from the `venia.core` bundle. 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

**Review by herzog31 — APPROVED** [review]
Looks good. 

You actually can use environment variables in cache names via `{{ .Environment.variableName }}`. They just have to be defined by CircleCI, not any script. See https://circleci.com/docs/2.0/configuration-reference/#save_cache.

**Comment by cjelger** [comment]
@herzog31 I tried to use `{{ .Environment.AEM }}` but it doesn't work, that's why I switched to the parameter.

**Comment by herzog31** [comment]
That's strange, since it works in https://github.com/adobe/aem-cif-guides-venia/pull/42/files#diff-1d37e48f9ceff6d8030570cd36286a61R36. Anyway, both approaches work :)

**Comment by cjelger** [comment]
It actually doesn't work, check the build logs:
```No cache is found for key: maven-repo-v1-aP7D0QrbShBQyYNtj4swWjbkvJRRepP5UyZN2YXJHFQ=-<no value>```

**Comment by herzog31** [comment]
Okay, then I need to fix that 😁

**Pull request merged**
