### PR TITLE
CIF-1609 - Lazy Loading for PLP

### PR DESCRIPTION
**Pull request by cjelger**
- adding css for the "load more" button and loading spinner
- fix bug that productlist component is not added to the initial content of the category-page

See https://github.com/adobe/aem-core-cif-components/pull/406 for screenshots.

### CODE REVIEW

**Comment by herzog31** [comment]
Is there any reason why you don't use the existing loader CSS from https://github.com/adobe/aem-cif-guides-venia/blob/main/ui.frontend/src/main/styles/commerce/_loadingindicator.scss?

**Comment by cjelger** [comment]
I initially wanted to have a loader that doesn't look like the Venia logo so that customers can simply copy the css if they don't want to redesign it, but I don't have a strong preference here.

**Comment by cjelger** [comment]
@herzog31 I checked again and actually the `css` is the React component itself at https://github.com/adobe/aem-core-cif-components/blob/master/react-components/src/components/LoadingIndicator/indicator.css so I cannot use it directly. I'd have had to duplicate it, and as I said, I prefer having a "generic" spinner that customers can potentially simply copy (if they like it).

**Review by herzog31 — APPROVED** [review]
@cjelger I don't have a strong opinion either. Just find a bit strange to abandon the Venia styling. Basically nothing in the Venia styling is generic.

**Review by dplaton — APPROVED** [review]

**Pull request merged**
