### PR TITLE
CIF-1084 - Implement the password reset page

### PR DESCRIPTION
**Pull request by herzog31**
## Description

* Adds a new `reset-password` page at `/content/venia/{language-master|us}/en/reset-password.html`.
* Adds a proxy component for new `resetpassword` component.
* Adds new `ResetPassword` React component to the React app.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

**Review by cjelger — COMMENTED** [review]
A generic comment and sorry if I haven't followed precisely: is this "reset password" a "forgot password" functionality that is used when a user forgot her/his password? If yes, then we should probably not have the page under "my-account" because the user cannot login, so I think it might be misleading to have this under "my-account".

**Comment by mhaack** [comment]
+1 to @cjelger 's comment plus additionally we should make sure if you are navigation to my-account pages/sub-pages without being logged in we should redirect to the homepage and if possible open the login form. Ideally, we should also have a dedicated login page where we would redirect to. But all this is a separate ticket.

**Comment by herzog31** [comment]
@cjelger @mhaack Magento Luma has it under the account tree. Any suggestions where the page should be?

**Comment by cjelger** [comment]
Maybe below `language-masters/en` ? Also make sure the page is hidden in the navigation like the search page (with `hideInNav` true). I agree with Markus about the redirect.

**Comment by herzog31** [comment]
@mhaack @cjelger I moved the reset password page to `/content/venia/{language-master|us}/en/reset-password.html`.

**Review by cjelger — APPROVED** [review]

**Review by mhaack — APPROVED** [review]

**Pull request merged**
